name       : tickrs
version    : 0.14.8
release    : 3
source     :
    - https://github.com/tarkah/tickrs/archive/refs/tags/v0.14.8.tar.gz : 5739a7ac77312ea5736457cc4bd91f499230069d8fb73f8b0c8544390a42cabe
license    : MIT
component  : network.news
summary    : Realtime ticker data in your terminal
description: |
    Realtime ticker data in your terminal. Built with Rust. Data sourced from Yahoo! Finance.
networking : yes
builddeps  :
    - pkgconfig(libcurl)
    - cargo
setup      : |
    %patch -p1 < $pkgfiles/0001-vendored-ssl.patch
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/tickrs $installdir/usr/bin/tickrs

