name       : tickrs
version    : 0.14.9
release    : 5
source     :
    - https://github.com/tarkah/tickrs/archive/refs/tags/v0.14.9.tar.gz : a633754e168a0d9a7488601c058a5056100ff74160f696d328870f70cb38047b
homepage   : https://github.com/tarkah/tickrs
license    : MIT
component  : network.news
summary    : Realtime ticker data in your terminal
description: |
    Realtime ticker data in your terminal. Built with Rust. Data sourced from Yahoo! Finance.
networking : yes
builddeps  :
    - pkgconfig(libcurl)
    - cargo
setup      : |
    %patch -p1 < $pkgfiles/0001-vendored-ssl.patch
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/tickrs $installdir/usr/bin/tickrs

