name       : tickrs
version    : 0.14.4
release    : 1
source     :
    - https://github.com/tarkah/tickrs/archive/refs/tags/v0.14.4.tar.gz : b0705cbdf148d942022266d84577d67c1b5217bac7e0d54d4ebdc5c067a855d6
license    : MIT
component  : network.news
summary    : Realtime ticker data in your terminal
description: |
    Realtime ticker data in your terminal. Built with Rust. Data sourced from Yahoo! Finance.
networking : yes    
builddeps  :
    - pkgconfig(libcurl)
    - cargo
setup      : |
    %patch -p1 < $pkgfiles/0001-vendored-ssl.patch
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/tickrs $installdir/usr/bin/tickrs

